name: errors-ext
version: 0.4.3
synopsis: "`bracket`-like functions for `ExceptT` over `IO` monad."
description: "`bracket`-like functions for `ExceptT` over `IO` monad."
github: "A1-Triard/errors-ext"
license: Apache
author: "Warlock <internalmike@gmail.com>"
maintainer: "Warlock <internalmike@gmail.com>"
copyright: "2017, 2018 Warlock <internalmike@gmail.com>"
category: Control, Error Handling
#extra-source-files:

dependencies:
- base >= 4.7 && < 5
- errors
- exceptions
- monad-control
- mtl
- transformers

default-extensions:
- FlexibleContexts

ghc-options:
- -fmax-pmcheck-iterations=100000000
- -Wall
- -fprint-potential-instances
- -fsimpl-tick-factor=110

library:
  source-dirs: src

tests:
  errors-ext-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - errors-ext
    - binary-ext >= 2.0.4
    - bytestring
    - conduit
    - monad-loops
    default-extensions:
    - BangPatterns
    - OverloadedStrings
